#!/bin/bash
TEST_INPUTS=resources/tests
TEST_OUTPUTS=save_files/save_tests

if [ -z "$4" ]; then
  OUTPUT=/dev/null
else
  OUTPUT="${TEST_OUTPUTS}/${3}_${4}.txt"
fi

if [ -z "$5" ]; then
  RUN_EXECUTABLE="${1}/${2}"
else
  RUN_EXECUTABLE="${1}/${2} -s $5"  
fi

./"${RUN_EXECUTABLE}" < "${TEST_INPUTS}/${3}/${3}_player.txt" > "${OUTPUT}"

if (diff "${TEST_INPUTS}/${3}/${3}_expected.txt" "${TEST_OUTPUTS}/${3}_output.txt"); then
  echo "Passed!"
else
  echo "Failed :("
fi
